personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/FoodLeisureServices/FoodLeisure.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.VisualBasic;

namespace personalised_concierge_m1.Models.Entities.FoodLeisureServices
{
    public enum FoodLeisureType
    {
        Restaurant,
        Hawker,
        POI,
        HotelFacilities
    }

    public class FoodLeisure
    {
        [Key]
        public int foodleisure_id { get; set; }

        [Required]
        [Column(TypeName = "varchar(50)")]
        public string name { get; set; }

        [Required]
        [Column(TypeName = "varchar(10000)")]
        public string description { get; set; }

        [Column(TypeName = "varchar(500)")]
        public string website_link { get; set; }

        [Required]
        [Column(TypeName = "varchar(20)")]
        public string contact_num { get; set; }

        [Column(TypeName = "varchar(500)")]
        public string foodleisure_image { get; set; }

        [Required]
        public FoodLeisureType type { get; set; }

        [Required]
        [Column(TypeName = "varchar(500)")]
        public string address { get; set; }

        [Required]
        [Column(TypeName = "boolean")]
        public Boolean featured { get; set; }


        [Column(TypeName = "varchar(100)")]
        public string businessHours { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string latitude { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string longtitude { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string email { get; set; }

        [Column(TypeName = "varchar(500)")]
        public string supportedLanguage { get; set; }

        [Column(TypeName = "varchar(100)")]
        public string nearestMRTStation { get; set; }

    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
using System;
using System.Dynamic;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using personalised_concierge_m1.Models.Interfaces;
using personalised_concierge_m1.Models.Entities.OtherServices;
using personalised_concierge_m1.Models.Entities.FoodLeisureServices;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace personalised_concierge_m1.Controllers
{
    public class FoodLeisureController : Controller
    {
        //Model Class will create a UnitOfWork to talk to Db.
        private readonly IM2UnitOfWork _m2UnitOfWork;
        private readonly IUnitOfWork _unitOfWork;


        public FoodLeisureController(IM2UnitOfWork m2UnitOfWork, IUnitOfWork m1UnitOfWork)
        {

            this._m2UnitOfWork = m2UnitOfWork;
            this._unitOfWork = m1UnitOfWork;

        }
        [HttpGet]
        public IActionResult Index()
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.restaurants = _m2UnitOfWork.FoodLeisureDetails.GetLimitedFoodLeisureBytype(FoodLeisureType.Restaurant);
            mymodel.pois = _m2UnitOfWork.FoodLeisureDetails.GetLimitedFoodLeisureBytype(FoodLeisureType.POI);
            mymodel.hawkers = _m2UnitOfWork.FoodLeisureDetails.GetLimitedFoodLeisureBytype(FoodLeisureType.Hawker);

            mymodel.featuredFoodLeisure = _m2UnitOfWork.FoodLeisureDetails.GetAllFoodLeisure();

            // Create the empty list of objects to store the featured foodleisure items
            List<FoodLeisure> featuredFoodLeisure = new List<FoodLeisure>();

            //! Check for the number of properties in the object
            // Type type = typeof(YourClassName);
            // int NumberOfRecords = type.GetProperties().Length;

            //! Loop through the dynamic model and add the object that has featured == true to the list
            foreach (var item in mymodel.featuredFoodLeisure)
            {
                if (item.featured == true)
                {
                    featuredFoodLeisure.Add(item);
                }
            }
            mymodel.featuredFoodLeisure = featuredFoodLeisure;


            return View(mymodel);
        }



        [HttpPost]
        public IActionResult SpecificFoodLeisure(int FoodLeisureID)
        {
            dynamic mymodel = new ExpandoObject();
            mymodel.foodLeisure = _m2UnitOfWork.FoodLeisureDetails.GetFoodLeisureByID(FoodLeisureID);
            mymodel.reviews = _m2UnitOfWork.ReviewDetails.GetReviewByFoodLeisure(FoodLeisureID);
            mymodel.businessreviews = _m2UnitOfWork.ReviewDetails.GetBusinessReviewByFoodLeisure(FoodLeisureID);
            mymodel.accounts = _unitOfWork.AccountDetails.GetAll();
            string review = Request.Form["Review_Description"];
            string sortsubmit = Request.Form["SortSubmit"];

            //Get sum of all ratings
            double totalratings = 0;
            double avgrating = 0.0;
            var count = 0;
            foreach (Review areview in mymodel.reviews)
            {

                count++;
                int ratingInt = (int)(Rating)Enum.Parse(typeof(Rating), areview.rating.ToString());
                totalratings += ratingInt;
                avgrating = Math.Round(totalratings / count, 3);
            }

            //Sort request received 
            if(sortsubmit != null)
            {
                string sort = Request.Form["sort"];
                string sortType = Request.Form["sort_type"];
                string searchstr = Request.Form["search_str"];

                // The client code picks a concrete strategy and passes it to the
                // context. The client should be aware of the differences between
                // strategies in order to make the right choice.
                var context = new Context();

                var sortReview = _m2UnitOfWork.ReviewDetails.GetReviewByFoodLeisure(FoodLeisureID);

                if (sort == "reviewid")
                {
                   context.SetStrategy(new FilterSortReviewIDStrategy(_m2UnitOfWork));
                    mymodel.reviews = context.DoSomeFilterSortingLogic(sortType, FoodLeisureID, searchstr);  
                }else if (sort == "ratings")
                {
                    context.SetStrategy(new FilterSortRatingsStrategy(_m2UnitOfWork));
                    mymodel.reviews = context.DoSomeFilterSortingLogic(sortType, FoodLeisureID, searchstr);
                }else if (sort == "date")
                {
                    context.SetStrategy(new FilterSortReviewDateStrategy(_m2UnitOfWork));
                    mymodel.reviews = context.DoSomeFilterSortingLogic(sortType, FoodLeisureID, searchstr);
                }else if(sort == "description")
                {
                    context.SetStrategy(new FilterSortDescriptionStrategy(_m2UnitOfWork));
                    mymodel.reviews = context.DoSomeFilterSortingLogic(sortType, FoodLeisureID, searchstr);
                }
            }

            //display even if there is no submision from review form 
            if (review != null)
            {

                string foodleisureID = Request.Form["foodLeisureID"];
                string ratings = Request.Form["Ratings"];
                var dateAsString = DateTime.Now.ToString("yyyy-MM-dd");
                string refreviewid = Request.Form["ref_review"];
                var rating = (Rating)Enum.Parse(typeof(Rating), ratings, true);
                IReview myReview = ReviewFactory.makeReview(refreviewid);
                var newReview = myReview.setReview(3, Int32.Parse(foodleisureID), review, dateAsString, rating, refreviewid);
                _m2UnitOfWork.ReviewDetails.Add(newReview);
                Boolean result = _m2UnitOfWork.ReviewDetails.Save();

                // if cannot submit review 
                if (!result)
                {
                    return NotFound();
                }
                else
                {
                    // all these for display after submit 
                    mymodel.reviews = _m2UnitOfWork.ReviewDetails.GetReviewByFoodLeisure(FoodLeisureID);
                    mymodel.businessreviews = _m2UnitOfWork.ReviewDetails.GetBusinessReviewByFoodLeisure(FoodLeisureID);
                    //count rating again on refresh ah!
                    totalratings = 0;
                    avgrating = 0.0;
                    count = 0;
                    foreach (Review areview in mymodel.reviews)
                    {
                        count++;
                        int ratingInt = (int)(Rating)Enum.Parse(typeof(Rating), areview.rating.ToString());
                        totalratings += ratingInt;
                        avgrating = Math.Round(totalratings / count, 3);

                        mymodel.totalrating = totalratings;
                        mymodel.avgrating = avgrating;
                    }



                    mymodel.totalrating = totalratings;
                    mymodel.avgrating = avgrating;
                    return View(mymodel);
                }
            }

            mymodel.totalrating = totalratings;
            mymodel.avgrating = avgrating;
            return View(mymodel);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/Index.cshtml
@using personalised_concierge_m1.Models.Entities.FoodLeisureServices
@model dynamic

@{}

<!DOCTYPE html>
<html>

<body>

    <h1 style="color: #0b65a1;" >Trip Planner Home</h1>

    <!---Banner Start-->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            @for (int i = 1; i < Model.featuredFoodLeisure.Count; i++)
            {
                <li data-target="#carouselExampleIndicators" data-slide-to="i"></li>
            }
        </ol>
        @* First item, set as active to be displayed first *@
        <div class="carousel-inner">
            <div class="carousel-item active">
                @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                {
                    <input type="hidden" name="FoodLeisureID" value="@Model.featuredFoodLeisure[0].foodleisure_id" />
                    <img class="d-block w-100" style="object-fit: contain;" src=@Url.Content(@Model.featuredFoodLeisure[0].foodleisure_image)
                         alt="First slide">
                    <div class="carousel-caption d-none d-md-block" style="background-color: grey; opacity: 0.8;">
                        <a style="font-weight:bold; font-size:30px" class="nav-link text-dark">
                            <input type="submit" style="border: none; background-color: transparent"
                                   value="@Model.featuredFoodLeisure[0].name" />
                        </a>
                        <p style="font-size:20px">@Model.featuredFoodLeisure[0].description</p>
                    </div>
                }
            </div>
            @* for loop to go through the rest of the featured items to be displayed *@
            @for (int i = 1; i < Model.featuredFoodLeisure.Count; i++)
            {
                <div class="carousel-item">
                    @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                    {
                        <input type="hidden" name="FoodLeisureID" value="@Model.featuredFoodLeisure[i].foodleisure_id" />
                        <img class="d-block w-100" src=@Url.Content(@Model.featuredFoodLeisure[i].foodleisure_image) alt="@Model.featuredFoodLeisure[i].name">
                        <div class="carousel-caption d-none d-md-block" style="background-color: grey; opacity: 0.8;">
                            <a style="font-weight:bold; font-size:30px" class="nav-link text-dark">
                                <input type="submit" style="border: none; background-color: transparent"
                                       value="@Model.featuredFoodLeisure[i].name" />
                            </a>
                            <p>@Model.featuredFoodLeisure[i].description</p>
                        </div>
                    }
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <!---Banner end-->
    <br/>
    <br />

    <div class="card">
        <div class="card-body">

            <h2 style="color: #0b65a1;">Search For Things to Do!</h2>
            @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
            {
                <input type="number" name="FoodLeisureID" />
                <br /><br />

                <input type="submit" value="Go Specific View" />
            }
            <br />
        </div>
    </div>
    <br/>
    <br />
    <ul class="nav nav-tabs" id="myTab" role="tablist" style="background-color: #fff9d9;">
        <li class="nav-item">
            <a class="nav-link active" id="restaurants-tab" data-toggle="tab" href="#restaurants" role="tab"
               aria-controls="restaurants" aria-selected="true">Restaurants</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="hawkers-tab" data-toggle="tab" href="#hawkers" role="tab" aria-controls="hawkers"
               aria-selected="false">Local Food (Hawkers)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="attractions-tab" data-toggle="tab" href="#attractions" role="tab"
               aria-controls="attractions" aria-selected="false">Tourist Attractions</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="restaurants" role="tabpanel" aria-labelledby="restaurants-tab">
            <br />
            <h2>Restaurants</h2>
            <br />
            <div class="row">
                @foreach (FoodLeisure foodLeisure in Model.restaurants)
                {
                    <div class="col-sm-4">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="@Url.Content(@foodLeisure.foodleisure_image)"
                                 alt="@foodLeisure.name">
                            <div class="card-body">
                                <h5 class="card-title">@foodLeisure.name</h5>
                                <p>Contact Number: @foodLeisure.contact_num</p>
                                <p>Visit Reservation Page: <a href="@foodLeisure.website_link">HERE!</a></p>
                                @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                                {

                                    @Html.Hidden("FoodLeisureID", (int)foodLeisure.foodleisure_id)

                                    <input type="submit" value="Go Specific View" style="background-color: #fff9d9;" />
                                }

                            </div>
                        </div>
                        <br />
                    </div>
                }

                <br />
            </div>
        </div>

        <div class="tab-pane fade" id="hawkers" role="tabpanel" aria-labelledby="hawkers-tab">
            <br />
            <h2>Hawkers</h2>
            <br />
            <div class="row">
                @foreach (FoodLeisure foodLeisure in Model.hawkers)
                {
                    <div class="col-sm-4">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="@Url.Content(@foodLeisure.foodleisure_image)"
                                 alt="@foodLeisure.name">
                            <div class="card-body">
                                <h5 class="card-title">@foodLeisure.name</h5>
                                <p>Contact Number: @foodLeisure.contact_num</p>
                                <p>Visit Reservation Page: <a href="@foodLeisure.website_link">HERE!</a></p>
                                @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                                {

                                    @Html.Hidden("FoodLeisureID", (int)foodLeisure.foodleisure_id)

                                    <input type="submit" value="Go Specific View" style="background-color: #fff9d9;" />
                                }

                            </div>
                        </div>
                        <br />
                    </div>
                }

                <br />
            </div>

        </div>
        <div class="tab-pane fade" id="attractions" role="tabpanel" aria-labelledby="attractions-tab">
            <br />
            <h2>Places Of Interest</h2>
            <br />
            <div class="row">
                @foreach (FoodLeisure foodLeisure in Model.pois)
                {
                    <div class="col-sm-4">
                        <div class="card" style="width: 18rem;">
                            <img class="card-img-top" src="@Url.Content(@foodLeisure.foodleisure_image)"
                                 alt="@foodLeisure.name">
                            <div class="card-body">
                                <h5 class="card-title">@foodLeisure.name</h5>
                                <p>Contact Number: @foodLeisure.contact_num</p>
                                <p>Visit Reservation Page: <a href="@foodLeisure.website_link">HERE!</a></p>
                                @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                                {

                                    @Html.Hidden("FoodLeisureID", (int)foodLeisure.foodleisure_id)

                                    <input type="submit" value="Go Specific View" style="background-color: #fff9d9;" />
                                }

                            </div>
                        </div>
                        <br />
                    </div>
                }

                <br />
            </div>


        </div>
    </div>




</body>

</html>

personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/SpecificFoodLeisure.cshtml
@using personalised_concierge_m1.Models.Entities.FoodLeisureServices
@using personalised_concierge_m1.Models.Entities.OtherServices
@using personalised_concierge_m1.Models.Entities.UserDetails
@model dynamic


@{

}

<!DOCTYPE html>
<html>

<body>

    <h1>Trip Planner Specific Item </h1>
    <p>Foodleisure Item Details Display here!</p>

    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card" style="width: 25rem;">
                    <img src="@Url.Content(@Model.foodLeisure.foodleisure_image)" class="card-img-top"
                         alt="@Model.foodLeisure.name">
                </div>
            </div>
            <div class="col">
                <h1>@Model.foodLeisure.name</h1>
                <h4>@Model.foodLeisure.address </h4>
                <h5>Contact Number: @Model.foodLeisure.contact_num</h5>
                <h5>Visit Reservation Page: <a href="@Model.foodLeisure.website_link">HERE!</a></h5>
                <h6>Email Us: @Model.foodLeisure.email</h6>
                <h6>Opening Hours: @Model.foodLeisure.businessHours</h6>
                <p>Category: @Model.foodLeisure.type</p>
                <p>@Model.foodLeisure.description</p>
                <br />
                <p>Nearest MRT Station: @Model.foodLeisure.nearestMRTStation</p>
            </div>
        </div>
    </div>

    <hr />

    <div class="container">
        <div class="row">
            <div class="col">
                <p>
                    <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#collapseExample"
                            aria-expanded="false" aria-controls="collapseExample">
                        Add Your Review
                    </button>

                </p>
            </div>

        </div>
    </div>

    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
            {


                @Html.TextArea("Review_Description", new { @cols = "100", @rows = "8", @style = "width:100%;" })

                <br />
                @Html.DropDownList("Ratings",
     new SelectList(Enum.GetValues(typeof(Rating))),
     "Ratings (out of 5)",
     new { @class = "form-control" })

                @Html.Hidden("foodLeisureID", (int)Model.foodLeisure.foodleisure_id)
                <br><br>
                <input type="submit" value="Submit">
            }

        </div>
        
    </div>
    </br>

    <!---searchsort box-->
    <div class="card">
        <div class="card-body">

            <h2 style="color: #0b65a1;">Search & Sort Review!</h2>
            @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
            {
                <p>Search:</p>
                <input type="text" name="search_str" />



                <input type="radio" id="ascending" name="sort_type" value="ascending"
                       checked>
                <label for="ascending">Ascending</label>

                <input type="radio" id="descending" name="sort_type" value="descending">
                <label for="descending">Descending</label>


                <input type="radio" id="search" name="sort_type" value="search">
                <label for="search">Search</label>

                <div class="form-group .col-">
                    <label for="sel1">Sort/Search By:</label>
                    <select class="form-control" name="sort" id="sel1">
                        <option value="reviewid">Review ID</option>
                        <option value="ratings">Ratings</option>
                        <option value="date">Date</option>
                        <option value="description">Review Description</option>
                    </select>
                </div>


                @Html.Hidden("foodLeisureID", (int)Model.foodLeisure.foodleisure_id)
                <input name="SortSubmit" type="submit" value="Submit">
            }
            <br />
        </div>
    </div>
    <!---END searchsort box-->
    <hr />


    <div class="container">
        <div class="row">

            <div class="col">
                <h1> Total ratings: @Model.totalrating</h1>
                <h2> Average ratings: @Model.avgrating / 5</h2>
                <hr />
                <div class="review-block">
                    @{int count = 0; }
                    @foreach (Review review in Model.reviews)
                    {
                        @foreach (Account account in Model.accounts)
                        {
                            @if (account.account_id == review.account_id)
                            {
                                string countString = count.ToString();
                                string target = "dataLine" + countString;
                                string trigger = "#" + target;
                                <div class="row">
                                    <div class="col-sm-3">
                                        <img style="width: 10rem; height: 10rem;" src="@Url.Content(@account.profile_pic)"
                                             class="img-rounded">
                                        <div class="review-block-name"><a href="#">@account.full_name</a></div>

                                        <div class="review-block-date">@account.email<br />Posted on: @review.Date</div>
                                    </div>
                                    <div class="col-sm-9">
                                        <h6>Ratings: @review.rating out of Five</h6>

                                        <div class="review-block-title">Review ID: @review.review_id</div>
                                        <div class="review-block-description">@review.review</div>
                                        <br />


                                        <p>
                                            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="@trigger"
                                                    aria-expanded="false" aria-controls="@review.review_id">
                                                Reply
                                            </button>
                                        </p>




                                        <!--Reply stuff-->

                                        <div class="collapse" id=@target>
                                            <div class="card card-body">
                                                @using (Html.BeginForm("SpecificFoodLeisure", "FoodLeisure"))
                                                {


                                                    @Html.TextArea("Review_Description", new { @cols = "100", @rows = "8", @style = "width:100%;" })

                                                    <br />


                                                    @Html.Hidden("foodLeisureID", (int)Model.foodLeisure.foodleisure_id)
                                                    @Html.Hidden("Ratings", 1)
                                                    @Html.Hidden("ref_review", @review.review_id)
                                                    <br><br>
                                                    <input type="submit" value="Submit">
                                                }

                                            </div>
                                        </div>
                                        <!--end of reply stuff-->
                                        <br />
                                        <div>
                                            @foreach (Review bisreview in Model.businessreviews)
                                            {
                                                @foreach (Account account2 in Model.accounts)
                                                {
                                                    @if (bisreview.refrence_review == review.review_id.ToString())
                                                    {
                                                        @if (account2.account_id == bisreview.account_id)
                                                        {
                                                            <div class="row">
                                                                <div class="col-sm-3">
                                                                    <img style="width: 10rem; height: 10rem;" src="@Url.Content(@account2.profile_pic)"
                                                                         class="img-rounded">
                                                                    <div class="review-block-name"><a href="#">@account2.full_name</a></div>

                                                                    <div class="review-block-date">@account2.email<br />Posted on: @bisreview.Date</div>
                                                                </div>
                                                                <div class="col-sm-9">
                                                                    <h6>Business User: @Model.foodLeisure.name Business Account</h6>
                                                                    <div class="review-block-title">Review ID: @bisreview.review_id</div>
                                                                    <div class="review-block-description">@bisreview.review</div>
                                                                    <br />
                                                                </div>
                                                            </div>
                                                            <br />
                                                        }




                                                    }
                                                }




                                            }


                                        </div>


                                    </div>
                                </div>
                                <br />

                                <hr />
                                count++;

                            }


                        }


                    }

                    <hr />
                </div>
            </div>
        </div>

    </div> <!-- /container -->




</body>

</html>