personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Itineraries/Calendar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using personalised_concierge_m1.Models;

namespace personalised_concierge_m1.Models
{
    public class Calendar
    {
        [Column("CalendarId")]
        [Key]
        private int calendarId;

        [Column("CreatedDate")]
        private DateTime createdDate;

        [Column("StartDate")]
        private DateTime startDate;

        [Column("EndDate")]
        private DateTime endDate;

        [NotMapped]
        private List<Calendar> calendarList;
        public int CalendarId
        {
            get { return calendarId; }
            set { calendarId = value; }
        }
        public DateTime CreatedDate
        {
            get { return createdDate; }
            set { createdDate = value; }
        }
        public DateTime StartDate
        {
            set { startDate = value; }
            get { return startDate; }
        }
        public DateTime EndDate
        {
            set { endDate = value; }
            get { return endDate; }
        }
        [NotMapped]
        public List<Calendar> CalendarList
        {
            set { calendarList = value; }
            get { return calendarList; }
        }
        public void createItinerary(DateTime createdDate, DateTime startDate, DateTime endDate)
        {
            CreatedDate = createdDate;
            StartDate = startDate;
            EndDate = endDate;
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using personalised_concierge_m1.Data;
using personalised_concierge_m1.Models;
using personalised_concierge_m1.Interface;
using personalised_concierge_m1.Models.Interfaces;

namespace personalised_concierge_m1.Controllers
{
    public class CalendarController : Controller
    {
        private Calendar calendar = new Calendar();
        private readonly IM2UnitOfWork _m2UnitOfWork;

        public CalendarController(IM2UnitOfWork m2UnitOfWork)
        {
            _m2UnitOfWork = m2UnitOfWork;

        }

        public IActionResult Index()
        {
            calendar.CalendarList = getAllCalendar();
            return View(calendar);
        }

        public List<Calendar> getAllCalendar()
        {
            return _m2UnitOfWork.CalendarDetails.getAllCalendar();
        }

        [HttpPost]
        public JsonResult createItinerary(string createdDate, string startDate, string endDate)
        {
            Calendar itinerary = new Calendar();
            itinerary.createItinerary(Convert.ToDateTime(createdDate), Convert.ToDateTime(startDate), Convert.ToDateTime(endDate));
            _m2UnitOfWork.CalendarDetails.addCalendar(itinerary);
            string itineraryObjString = JsonConvert.SerializeObject(itinerary);
            return new JsonResult(itineraryObjString);
        }

        [HttpPost]
        public JsonResult deleteCalendar(int id)
        {
            Calendar itinerary = new Calendar();
            _m2UnitOfWork.CalendarDetails.deleteCalendar(id);
            _m2UnitOfWork.CalendarEventDetails.cascadeDelete(id);
            string itineraryObjString = JsonConvert.SerializeObject(itinerary);
            return new JsonResult(itineraryObjString);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/CalendarEventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using personalised_concierge_m1.Data;
using personalised_concierge_m1.Models;
using personalised_concierge_m1.Interface;
using personalised_concierge_m1.Modelspersonalised_concierge_m1.Models;
using personalised_concierge_m1.Models.Interfaces;

namespace personalised_concierge_m1.Controllers
{
    public class CalendarEventController : Controller
    {
        private CalendarEvent calendarEvent = new CalendarEvent();
        private readonly IM2UnitOfWork _m2UnitOfWork;
        private static int currentCalendarId;

        public CalendarEventController(IM2UnitOfWork m2UnitOfWork)
        {
            _m2UnitOfWork = m2UnitOfWork;
        }

        public IActionResult Index()
        {
            calendarEvent = getAllCalendarEvent();
            return View(calendarEvent);
        }

        public CalendarEvent getAllCalendarEvent()
        {
            var calendarEventList = _m2UnitOfWork.CalendarEventDetails.getAllEventById(currentCalendarId);
            //datetime is in this format after retrieve from db: 8/3/2022 12:00:00 am
            calendarEvent.CalendarEventList = calendarEventList;
            return calendarEvent;
        }

        [HttpPost]
        public JsonResult createEvent(int id, string name, string type, string location, string description, string date, string startTime, string endTime, string note, int otherId)
        {
            if (id == 0) // adding new entry to calendarEvent table 
            {
                ICalendarEvent calendarEvent1 = CalendarEventFactory.makeCalendarEvent(type, otherId);
                CalendarEvent calendarEvent = calendarEvent1.createCalendarEventObj(name, location, type, description, date, startTime, endTime, note);
                calendarEvent.CalendarId = currentCalendarId;
                //CalendarEvent calendarEvent = setCalendarEventObject(name, location, type, description, date, startTime, endTime, note, otherId);
                _m2UnitOfWork.CalendarEventDetails.addEvent(calendarEvent);
                string jsonString = JsonConvert.SerializeObject(calendarEvent);
                return new JsonResult(jsonString);
            }
            else // updating calendarEvent with id specified
            {
                ICalendarEvent calendarEvent1 = CalendarEventFactory.makeCalendarEvent(type, otherId);
                CalendarEvent calendarEvent = calendarEvent1.updateCalendarEventObj(id, name, type, location, description, date, startTime, endTime, note);
                calendarEvent.CalendarId = currentCalendarId;
                //CalendarEvent calendarEvent = setCalendarEventObjectWithId(id, name, type, location, description, date, startTime, endTime, note, otherId);
                _m2UnitOfWork.CalendarEventDetails.updateEvent(calendarEvent);
                string jsonString = JsonConvert.SerializeObject(calendarEvent);
                return new JsonResult(jsonString);
            }

        }

        [HttpPost]
        public JsonResult retrieveEvent(int eventId)
        {
            var calendarEvent = _m2UnitOfWork.CalendarEventDetails.getEventByEventId(currentCalendarId, eventId);
            string jsonString = JsonConvert.SerializeObject(calendarEvent);
            return new JsonResult(jsonString);
        }

        public JsonResult deleteEvent(int eventId)
        {
            _m2UnitOfWork.CalendarEventDetails.deleteEvent(currentCalendarId, eventId);
            string jsonString = JsonConvert.SerializeObject(calendarEvent);
            return new JsonResult(jsonString);
        }

        public JsonResult retrieveAttraction(int id)
        {
            var attraction = _m2UnitOfWork.AttractionDemoDetails.findAttractionById(id);
            string jsonString = JsonConvert.SerializeObject(attraction);
            return new JsonResult(jsonString);
        }

        public JsonResult getInitialDate()
        {
            var calendarObj = _m2UnitOfWork.CalendarEventDetails.getCalendarDetails(currentCalendarId);
            string jsonString = JsonConvert.SerializeObject(calendarObj);
            return new JsonResult(jsonString);
        }

        public JsonResult postId(int id)
        {
            currentCalendarId = id;
            string jsonString = JsonConvert.SerializeObject(calendarEvent);
            return new JsonResult(jsonString);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Views/Calendar/Index.cshtml
@model personalised_concierge_m1.Models.Calendar

@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <title>Index</title>
</head>
<body>
    <div class="d-flex">
        <h3>Upcoming trips</h3>
        <button type="button" onclick="datePickerModal()" class="btn btn-info ml-auto">Create a new trip</button>
    </div>
    <br />

    <div class="row">
        @foreach (Calendar calendar in Model.CalendarList)
        {
            var startDate = @calendar.StartDate.ToString("dd MMMM yyyy");
            var endDate = @calendar.EndDate.ToString("dd MMMM yyyy");
            var createdDate = @calendar.CreatedDate.ToString("dd MMMM yyyy");
            <div class="card-group col-4" id="card/@calendar.CalendarId">
                <div class="card" onclick=postId(@calendar.CalendarId)>
                    <div class="img-wrap">
                        <img class="card-img-top" src="~/Images/MBS.jpg" alt="MBS image">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Trip in Singapore</h5>
                        <p class="card-text">@startDate - @endDate</p>
                        <p class="card-text">
                            <small class="text-muted">Created At: @createdDate</small>
                            <button type="button" onclick="deleteCalendar(@calendar.CalendarId)" class="btn btn-light float-right shadow-none"><i class="fa fa-trash"></i></button>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</body>

<!-- Modal -->
<div class="modal fade" id="datePickerModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Itinerary Planner</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-sm-6">
                        <label for="datepicker">From</label>
                        <input type="date" class="form-control" id="datepicker">
                    </div>

                    <div class="form-group col-sm-6">
                        <label for="datepicker2">To</label>
                        <input type="date" class="form-control" id="datepicker2">
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    <button type="button" onclick="createItinerary()" class="btn btn-info rounded-pill mt-3">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>
</html>
<script type="text/javascript">
    function createItinerary() {
        var from = document.getElementById("datepicker").value
        var to = document.getElementById("datepicker2").value
        var now = getCurrentDate();
        $.ajax({
            type: "POST",
            url: '@Url.Action("createItinerary", "Calendar")',
            data: {
                createdDate: now,
                startDate: from,
                endDate: to
            },
            dataType: 'json',
            success: function (result) {
                var obj = JSON.parse(result);
                location.reload();
                console.log(obj)
            }
        })
    }

    function postId(id) {
        event.stopPropagation();
            $.ajax({
            type: "POST",
            url: '@Url.Action("postId", "CalendarEvent")',
            data: {
                id: id
            },
            dataType: 'json',
            success: function (result) {
                location.href = "/CalendarEvent/Index";
            }
        })
    }

    function deleteCalendar(id) {
        event.stopPropagation();
            $.ajax({
            type: "POST",
            url: '@Url.Action("deleteCalendar", "Calendar")',
            data: {
                id: id
            },
            dataType: 'json',
            success: function (result) {
                var elementId = "card/" + id
                var element = document.getElementById(elementId);
                element.parentNode.removeChild(element);
            }
        })
    }

    function getCurrentDate() {
        const today = new Date();
        const yyyy = today.getFullYear();
        let mm = today.getMonth() + 1; // Months start at 0!
        let dd = today.getDate();

        if (dd < 10) dd = '0' + dd;
        if (mm < 10) mm = '0' + mm;

        var todayString = dd + '/' + mm + '/' + yyyy;
        return todayString
    }

    function datePickerModal() {
        $("#datePickerModal").modal('show');
    }
</script>