personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Attraction/Attraction.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.VisualBasic;
using personalised_concierge_m1.Models.Entities.UserDetails;
namespace personalised_concierge_m1.Models.Entities.Attraction
{
    public class Attraction
    {

        [Key]
        public int attractionId { get; set; }

        [Required]
        public string attractionName { get; set; }

        [Required]
        public string attractionImage { get; set; }

        [Required]
        public string attractionDescription { get; set; }

        [Required]
        public double attractionPrice { get; set; }

        [Required]

        public int attractionVote { get; set; }

        //public string attraction_location { get; set; }



    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Attraction/AttractionLocation.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.VisualBasic;
using personalised_concierge_m1.Models.Entities.UserDetails;
namespace personalised_concierge_m1.Models.Entities.Attraction
{
    public class AttractionLocation
    {

        public string attractionAddress { get; set; }
        public double attractionLat { get; set; }
        public double attractionLon { get; set; }

    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Attraction/AttractionVote.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.VisualBasic;
using personalised_concierge_m1.Models.Entities.UserDetails;
namespace personalised_concierge_m1.Models.Entities.Attraction
{
    public class AttractionVote
    {

        public int attractionVote { get; set; }

    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttraction.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttraction
    {
        IAttraction getAttractionById(int id);
        IAttraction getAttractionByName(string name);
        IAttraction getAttractionByPrice(double price);

    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttractionLocation.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttractionLocation
    {
        IAttractionLocation getAttractionLocationByAddress(string address);

    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttractionLocationRepo.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttractionLocationRepo
    {
        IAttractionLocationRepo getAllAttractionLocations();
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttractionRepo.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttractionRepo
    {
        IAttractionRepo getAllAttractions();
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttractionVote.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttractionVote
    {
        IAttractionVote getAttractionByVote(int vote);
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Attractions/IAttractionVoteRepo.cs
namespace personalised_concierge_m1.Models.Interfaces.Attraction
{
    public interface IAttractionVoteRepo
    {
        IAttractionVoteRepo getAllAttractionVotes();
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/AttractionController.cs
using Microsoft.AspNetCore.Mvc;
using personalised_concierge_m1.Models.Entities.Attraction;
using System;
using System.IO;
using System.Net;
using System.Xml;
using System.Device.Location;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;

namespace personalised_concierge_m1.Controllers
{
    public class AttractionController : Controller
    {
        private Attraction attraction = new Attraction();

        List<Attraction> attractionList = new List<Attraction>(){
                new Attraction{attractionId = 0, attractionName = "Universal Studio Singapore", attractionImage = "https://coveringmiles.com/wp-content/uploads/Universal-Studio-Singapore/uss-singapore.jpg", attractionDescription = "Universal Studios Singapore is a theme park located within the Resorts World Sentosa at Sentosa, Singapore. It features 28 rides, shows, and attractions in seven themed zones. It is one of the six Universal Studios theme parks around the world.", attractionPrice = 50, attractionVote = 57},
                new Attraction{attractionId = 1, attractionName = "Changi Airport", attractionImage = "https://wallpapercave.com/wp/wp4706740.jpg", attractionDescription = "Singapore Changi Airport, commonly known as Changi Airport, is a major civilian international airport that serves Singapore, and is one of the largest transportation hubs in Asia.", attractionPrice = 100, attractionVote = 40},
                new Attraction{attractionId = 2, attractionName = "Jurong Bird Park", attractionImage = "https://th.bing.com/th/id/R.1f1bf7056975fd71e503a15cfef4b00b?rik=Bq0FHjx3OwWirA&riu=http%3a%2f%2fimg.hulutrip.com%2f2016%2f0912%2f20160912051648928.jpg&ehk=YurTVEiVktxaOXhmxi58XnL5YHEj%2fB8rAVDUB5LN8D8%3d&risl=&pid=ImgRaw&r=0", attractionDescription = "Jurong Bird Park is an aviary and tourist attraction in Jurong, Singapore. The bird park covers an area of 0.2 square kilometres on the western slope of Jurong Hill, the highest point in the Jurong region.", attractionPrice = 20, attractionVote = 30},
                new Attraction{attractionId = 3, attractionName = "Singapore Zoo", attractionImage = "https://th.bing.com/th/id/R.06aa49218323a2e9e828de57411fd1b1?rik=Hr4SOwkUW5DdwA&riu=http%3a%2f%2fwww.wheninmanila.com%2fwp-content%2fuploads%2f2015%2f11%2fIMG_20151019_182918-01-e1447168453303.jpeg&ehk=t0kAYaRCr8sL%2fY2s%2fbrNU5jNfdJJ6zSusAC8ykKS%2fyY%3d&risl=&pid=ImgRaw&r=0", attractionDescription = "The Singapore Zoo, formerly known as the Singapore Zoological Gardens or Mandai Zoo, occupies 28 hectares on the margins of Upper Seletar Reservoir within Singapore's heavily forested central catchment area.", attractionPrice = 30, attractionVote = 108},
                new Attraction{attractionId = 4, attractionName = "Marina Bay Sands", attractionImage = "https://backiee.com/static/wpdb/wallpapers/1920x1080/239533.jpg", attractionDescription = "Marina Bay Sands is a destination for those who appreciate luxury. An integrated resort notable for transforming Singapore’s city skyline, it comprises three 55-storey towers of extravagant hotel rooms and luxury suites with personal butler services.", attractionPrice = 40, attractionVote = 89},
                new Attraction{attractionId = 5, attractionName = "Gardens by the Bay", attractionImage = "https://th.bing.com/th/id/R.e5637d0360bc83a02b5caf201185a608?rik=SxtD%2fWQzVRiXzg&riu=http%3a%2f%2fwww.marriedtoplants.com%2fwp-content%2fuploads%2f2016%2f08%2fgardens-by-the-bay-supertree-walk_.jpg&ehk=yruJFhWouk2KyIQfqDy5l83xZ6w9NnfauYigouKDvXc%3d&risl=&pid=ImgRaw&r=0", attractionDescription = "The Gardens by the Bay is a nature park spanning 101 hectares in the Central Region of Singapore, adjacent to the Marina Reservoir. The park consists of three waterfront gardens: Bay South Garden, Bay East Garden and Bay Central Garden.", attractionPrice = 60, attractionVote = 72},
                new Attraction{attractionId = 6, attractionName = "Singapore Botanic Gardens", attractionImage = "https://mustsharenews.com/wp-content/uploads/2015/07/THIS.jpg", attractionDescription = "The Singapore Botanic Gardens is a 163-year-old tropical garden located at the fringe of the Orchard Road shopping district in Singapore. It is one of three gardens, and the only tropical garden, to be honoured as a UNESCO World Heritage Site. The Botanic Gardens has been ranked Asia's top park attraction since 2013, by TripAdvisor Travellers' Choice Awards. It was declared the inaugural Garden of the Year, International Garden Tourism Awards in 2012, and received Michelin's three-star rating in 2008.", attractionPrice = 80, attractionVote = 90},
                new Attraction{attractionId = 7, attractionName = "National Orchid Garden", attractionImage = "https://www.singaporetravelhub.com/wp-content/uploads/2017/08/National-Orchid-Garden-05.jpg?x47978", attractionDescription = "The Singapore Botanic Gardens has been developed along a 3-Core Concept. The three Cores consist of Tanglin, which is the heritage core that retains the old favourites and rustic charms of the historic Gardens; Central, which is the tourist belt of the Gardens; and Bukit Timah, which is the educational and recreational zone. Each Core offers an array of attractions.", attractionPrice = 30, attractionVote = 32},
                new Attraction{attractionId = 8, attractionName = "Marina Barrage", attractionImage = "https://i.ytimg.com/vi/ith1yDFzVcc/maxresdefault.jpg", attractionDescription = "Built across the mouth of Marina Channel, Marina Barrage (MB) creates Singapore’s 15th reservoir, and the first in the heart of the city. With a catchment area of 10,000 hectares, Marina catchment is the island’s largest and most urbanised catchment. Together with two other reservoirs, Marina Reservoir has increased Singapore’s water catchment from half to two-thirds of the country’s land area.", attractionPrice = 20, attractionVote = 121},
                new Attraction{attractionId = 9, attractionName = "ArtScience Museum", attractionImage = "https://live.staticflickr.com/6064/6140047055_7d12ff66c2_b.jpg", attractionDescription = "As the name suggests, ArtScience Museum at Marina Bay Sands beautifully fuses art and science to tell fascinating stories. This premier venue houses a constantly changing line-up of major international touring exhibitions, brought in through collaborations with organisations such as the American Museum of Natural History, the Smithsonian Institute and world-renowned furniture designer Herman Miller.", attractionPrice = 20, attractionVote = 31}
            };

        public IActionResult Index()
        {
            return View(attractionList);
        }

        public async Task<IActionResult> ViewDetails(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (attraction == null)
            {
                return NotFound();
            }

            return View(attractionList[id]);
        }

        GeoCoordinateWatcher geo = null;

       
        
        public double GetDrivingDistanceInMiles(string origin, string destination)
        {

            string url = "https://maps.googleapis.com/maps/api/distancematrix/xml?origins=" + origin + "&destinations=" + destination + "&mode=driving&sensor=false&language=en-EN&units=imperial&key=AIzaSyDTTYqC1kZafWB0Ewsobhe05TyHGzl40qA";

            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            WebResponse response = request.GetResponse();
            Stream dataStream = response.GetResponseStream();
            StreamReader sreader = new StreamReader(dataStream);
            string responsereader = sreader.ReadToEnd();
            response.Close();
            XmlDocument xmldoc = new XmlDocument();
            xmldoc.LoadXml(responsereader);
            if (xmldoc.GetElementsByTagName("status")[0].ChildNodes[0].InnerText == "OK")
            {
                XmlNodeList distance = xmldoc.GetElementsByTagName("distance");
                return Convert.ToDouble(distance[0].ChildNodes[1].InnerText.Replace(" mi", ""));
            }


            return 0;
        }
        public string GetLocation(double latitude, double longitude)
        {
            string url = "https://maps.googleapis.com/maps/api/geocode/xml?latlng=" + latitude + "," + longitude + "&sensor=false&key=AIzaSyDTTYqC1kZafWB0Ewsobhe05TyHGzl40qA";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            WebResponse response = request.GetResponse();
            Stream dataStream = response.GetResponseStream();
            StreamReader sreader = new StreamReader(dataStream);
            string responsereader = sreader.ReadToEnd();
            response.Close();
            XmlDocument xmldoc = new XmlDocument();
            xmldoc.LoadXml(responsereader);
            if (xmldoc.GetElementsByTagName("status")[0].ChildNodes[0].InnerText == "OK")
            {
                XmlNodeList location = xmldoc.GetElementsByTagName("distance");
                return xmldoc.GetElementsByTagName("formatted_address")[0].ChildNodes[0].InnerText;
            }

            return "";
        }
        public IActionResult Suggestion()
        {
            GeoCoordinateWatcher watcher = new GeoCoordinateWatcher();

            // Do not suppress prompt, and wait 1000 milliseconds to start.
            watcher.TryStart(false, TimeSpan.FromMilliseconds(1000));

            GeoCoordinate coord = watcher.Position.Location;

            string Sentosa = GetLocation(1.2494, 103.8303);
            string changiairport = GetLocation(1.359167, 103.989441);
            string jurongbirdpark = GetLocation(1.318707, 103.706442);
            string zoo = GetLocation(1.4043, 103.7930);
            string mbs = GetLocation(1.2847, 103.8610);
            string gardenbay = GetLocation(1.2816, 103.8636);
            string orchidgarden = GetLocation(1.3127, 103.8137);

personalised_conceirge_m2/personalised_concierge_m1/Controllers/NavigationController.cs
using Microsoft.AspNetCore.Mvc;
using personalised_concierge_m1.Models.Entities.Navigation;

namespace personalised_concierge_m1.Controllers
{
    public class NavigationController : Controller
    {
        private Navigation navigation = new Navigation();

        public IActionResult Index()
        {
            return View(navigation);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/Index.cshtml
@model IEnumerable<personalised_concierge_m1.Models.Entities.Attraction.Attraction>
<!DOCTYPE html>
<html>
      
<head>
    <script language="javascript" type="text/javascript">
        // JavaScript code
        function search_attraction() {
            let input = document.getElementById('searchbar').value
            input=input.toLowerCase();
            let attractionName = document.getElementsByClassName('attractionName');
            let box = document.getElementsByClassName('sgLi');
            //let attractionDist = document.getElementsByClassName('attractionDist');
            let attractionVote = document.getElementsByClassName('attractionVote');

            split = input.split(" ");
      
            for (i = 0; i < attractionName.length; i++) { 
                count = 0;
                for (a = 0; a < split.length; a++){
                    //if (attractionName[i].innerHTML.toLowerCase().includes(split[a]) || attractionDist[i].innerHTML.toLowerCase().includes(split[a])) {
                    if (attractionName[i].innerHTML.toLowerCase().includes(split[a]) || parseInt(split[a]) <= parseInt(attractionVote[i].innerHTML)) {    
                        count += 1;
                    }
                }
                if (count != split.length){
                    box[i].style.display="none";
                }
                else{
                    box[i].style.display="inline-flex";
                }
            }
        }


        function upVote(clicked_id){
                
            let attractionVote = document.getElementsByClassName('attractionVote');


            
            for(i = 0; i < attractionVote.length+1; i++){
                var counter = 0;
                
                if(i == clicked_id){
                counter += parseInt(attractionVote[i].innerHTML);
                counter += 1
                attractionVote[i].innerHTML = counter.toString();
                document.getElementById(i.toString()).disabled = true;
                }      

                console.log(clicked_id)
                console.log(attractionVote[i].innerHTML);

            }
        }

        function downVote(clicked_id){
            let attractionVote = document.getElementsByClassName('attractionVote');
            let attractionName = document.getElementsByClassName('attractionName');
            for(i = 0; i < attractionVote.length; i++){
                var counter = 0;

                if(attractionName[i].innerHTML == clicked_id){
                counter += parseFloat(attractionVote[i].innerHTML);
                counter -= 1
                attractionVote[i].innerHTML = counter.toString();
                document.getElementById(attractionName[i].innerHTML).disabled = true;
                }
                console.log(clicked_id)
                console.log(attractionVote[i].innerHTML);
            }
        }

    </script>
      
    <!-- linking the stylesheet(CSS) -->
    <link rel="stylesheet" type="text/css" href="./style.css">
    <style>

     #searchbar{
         margin-left: 15%;
         padding:15px;
         border-radius: 10px;
     }
 
     input[type=text] {
          width: 70%;
          -webkit-transition: width 0.15s ease-in-out;
          transition: width 0.15s ease-in-out;
     }
 
      #list{
        font-size:  1.2em;
        margin-left: 90px;
       }
 
    .attraction{
       display: list-item;    
      }

    .X{
          margin: auto;
          padding: 1% 2%;
          max-width: 1440px;
          border-radius: 5px;
          background: #ecf0f1;
          box-shadow: 0 2px 6px 0 rgba(0,0,0, .3);
    }
    h1,h2,h3{
      text-align: center;
      font-family: 'Baloo Tamma', cursive;
    }
    
    /*SG = style grid*/
    .SG{
      margin: 0;
      padding: 0;
      text-align: center;
    }
    .SG .sgLi{
      min-width: 24%;
      margin: 2% .35%;
      display: inline-flex;
      box-shadow: 0 2px 4px rgba(0,0,0, .2);
    }
    .SG .sgLi:hover{
      box-shadow:0 5px 10px rgba(0,0,0,.15);}

    .SG .box{
      width: 350px;
      height: 350px;

      padding: 1% 2%;
      background: #fff;
      box-sizing: border-box;
      position: relative;
    }

    .box img {
        position: center;
        bottom: 15%;
        left: 8.33%;
    }

    .attractionDetailBtn{
        background-color: yellow;
        position: absolute;
        bottom: 5%;
        left: 35%;
    }


    </style>
</head>
  
<body>
      
    <div class="X">
        <!-- input tag -->
        <input id="searchbar" onkeyup="search_attraction()" type="text"
            name="search" placeholder="Search attractions here...">
      
        <ul class="SG">
            @foreach (var item in Model) {
                <li class="sgLi"> 
                <div class="box">
                    <h4 class="attractionName">@Html.DisplayFor(modelItem => item.attractionName)</h4>
                    <h7>Vote:</h7>
                    <h7 class="attractionVote">@Html.DisplayFor(modelItem => item.attractionVote)</h7><br>
                    <button id="@Html.DisplayFor(modelItem => item.attractionId)" onclick="upVote(this.id)">UP VOTE</button>
                    <button id="@Html.DisplayFor(modelItem => item.attractionName)" onclick="downVote(this.id)">DOWN VOTE</button><br><br>
                    <p><img src = "@Html.DisplayFor(modelItem => item.attractionImage)" width="250" height="150"/></p>
                    <!-- <a class="attractionDetailBtn" asp-route-id = "@item.attractionId" asp-controller="Attraction" asp-action="ViewDetails">View Details</a> -->


                    @using (Html.BeginForm("ViewDetails", "Attraction"))
                                {
                                    @Html.Hidden("id", (int)item.attractionId)

                                    <input type="submit" value="View Details" class="custom-btn" />
                                }
                </div>
                </li>
            }
            
        </ul>
      
        <!-- linking javascript -->
        <script src="./attraction.js"></script>
    </div>
</body>

  
</html>

<style>
    .custom-btn {
      appearance: none;
      background-color: #FAFBFC;
      border: 1px solid rgba(27, 31, 35, 0.15);
      border-radius: 6px;
      box-shadow: rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 1px 0 inset;
      box-sizing: border-box;
      color: #24292E;
      cursor: pointer;
      display: inline-block;
      font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
      font-size: 14px;
      font-weight: 500;
      line-height: 20px;
      list-style: none;
      padding: 6px 16px;
      position: relative;
      transition: background-color 0.2s cubic-bezier(0.3, 0, 0.5, 1);
      user-select: none;
      -webkit-user-select: none;
      touch-action: manipulation;
      vertical-align: middle;
      white-space: nowrap;
      word-wrap: break-word;
      margin-bottom: 10px;
    }

    .custom-btn:hover {
      background-color: #F3F4F6;
      text-decoration: none;
      transition-duration: 0.1s;
    }

    .custom-btn:disabled {
      background-color: #FAFBFC;
      border-color: rgba(27, 31, 35, 0.15);
      color: #959DA5;
      cursor: default;
    }

    .custom-btn:active {
      background-color: #EDEFF2;
      box-shadow: rgba(225, 228, 232, 0.2) 0 1px 0 inset;
      transition: none 0s;
    }

    .custom-btn:focus {
      outline: 1px transparent;
    }

    .custom-btn:before {
      display: none;
    }

    .custom-btn:-webkit-details-marker {
      display: none;
    }
</style>

personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/ViewDetails.cshtml
@model personalised_concierge_m1.Models.Entities.Attraction.Attraction
@{
    ViewData["Title"] = "ViewDetails";
}

<h1>Details</h1>
<ul class="SG">
    <li class="sgLi">
    <div class="box">
        <p><img src = "@Html.DisplayFor(model => model.attractionImage)" width="250" height="150"/></p>
        <h4>@Html.DisplayFor(model => model.attractionName)</h4>
        <h6 style="text-align: left;">@Html.DisplayFor(model => model.attractionDescription)</h6>
         @using (Html.BeginForm("Index", "Navigation"))
                                {
                                    @Html.Hidden("id", Model.attractionId)
                                    <input type="submit" value="Direction" class="custom-btn"/>
                                }
    </div>
    </li>
</ul>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<link rel="stylesheet" type="text/css" href="./style.css">
    <style>
        /*SG = style grid*/
    .SG{
      margin: 0;
      padding: 0;
      text-align: center;
    }
    .SG .sgLi{
      min-width: 24%;
      margin: 2% .35%;
      display: inline-flex;
      box-shadow: 0 2px 4px rgba(0,0,0, .2);
    }
    .SG .sgLi:hover{
      box-shadow:0 5px 10px rgba(0,0,0,.15);}

    .custom-btn {
      appearance: none;
      background-color: #FAFBFC;
      border: 1px solid rgba(27, 31, 35, 0.15);
      border-radius: 6px;
      box-shadow: rgba(27, 31, 35, 0.04) 0 1px 0, rgba(255, 255, 255, 0.25) 0 1px 0 inset;
      box-sizing: border-box;
      color: #24292E;
      cursor: pointer;
      display: inline-block;
      font-family: -apple-system, system-ui, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
      font-size: 14px;
      font-weight: 500;
      line-height: 20px;
      list-style: none;
      padding: 6px 16px;
      position: relative;
      transition: background-color 0.2s cubic-bezier(0.3, 0, 0.5, 1);
      user-select: none;
      -webkit-user-select: none;
      touch-action: manipulation;
      vertical-align: middle;
      white-space: nowrap;
      word-wrap: break-word;
      margin-bottom: 10px;
    }

    .custom-btn:hover {
      background-color: #F3F4F6;
      text-decoration: none;
      transition-duration: 0.1s;
    }

    .custom-btn:disabled {
      background-color: #FAFBFC;
      border-color: rgba(27, 31, 35, 0.15);
      color: #959DA5;
      cursor: default;
    }

    .custom-btn:active {
      background-color: #EDEFF2;
      box-shadow: rgba(225, 228, 232, 0.2) 0 1px 0 inset;
      transition: none 0s;
    }

    .custom-btn:focus {
      outline: 1px transparent;
    }

    .custom-btn:before {
      display: none;
    }

    .custom-btn:-webkit-details-marker {
      display: none;
    }
    </style>