personalised_conceirge_m2/personalised_concierge_m1/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using personalised_concierge_m1.Data;
using personalised_concierge_m1.Models;
using personalised_concierge_m1.Interface;
using personalised_concierge_m1.Models.Interfaces;

namespace personalised_concierge_m1.Controllers
{
    public class CalendarController : Controller
    {
        private Calendar calendar = new Calendar();
        private readonly IM2UnitOfWork _m2UnitOfWork;

        public CalendarController(IM2UnitOfWork m2UnitOfWork)
        {
            _m2UnitOfWork = m2UnitOfWork;

        }

        public IActionResult Index()
        {
            calendar.CalendarList = getAllCalendar();
            return View(calendar);
        }

        public List<Calendar> getAllCalendar()
        {
            return _m2UnitOfWork.CalendarDetails.getAllCalendar();
        }

        [HttpPost]
        public JsonResult createItinerary(string createdDate, string startDate, string endDate)
        {
            Calendar itinerary = new Calendar();
            itinerary.createItinerary(Convert.ToDateTime(createdDate), Convert.ToDateTime(startDate), Convert.ToDateTime(endDate));
            _m2UnitOfWork.CalendarDetails.addCalendar(itinerary);
            string itineraryObjString = JsonConvert.SerializeObject(itinerary);
            return new JsonResult(itineraryObjString);
        }

        [HttpPost]
        public JsonResult deleteCalendar(int id)
        {
            Calendar itinerary = new Calendar();
            _m2UnitOfWork.CalendarDetails.deleteCalendar(id);
            _m2UnitOfWork.CalendarEventDetails.cascadeDelete(id);
            string itineraryObjString = JsonConvert.SerializeObject(itinerary);
            return new JsonResult(itineraryObjString);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/ItineraryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using personalised_concierge_m1.Models.Interfaces.Itineraries;
using personalised_concierge_m1.Models.Entities.Itineraries;
using personalised_concierge_m1.Data.Itineraries;
using personalised_concierge_m1.Models.Interfaces;

namespace personalised_concierge_m1.Controllers
{
    public class ItineraryController : Controller
    {
        private Itinerary itinerary = new Itinerary();

        private readonly IM2UnitOfWork _m2UnitOfWork;

        public ItineraryController(IM2UnitOfWork m2UnitOfWork)
        {
            _m2UnitOfWork = m2UnitOfWork;
        }

        public IActionResult Index() { 
        
            return View(itinerary);
        }
        public IActionResult Testing()
        {

            return View();
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Controllers/NavigationController.cs
using Microsoft.AspNetCore.Mvc;
using personalised_concierge_m1.Models.Entities.Navigation;

namespace personalised_concierge_m1.Controllers
{
    public class NavigationController : Controller
    {
        private Navigation navigation = new Navigation();

        public IActionResult Index()
        {
            return View(navigation);
        }
    }
}

personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!--
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - personalised_concierge_m1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Personal Concierge</title>
    <!-- Iconic Fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="../vendors/iconic-fonts/font-awesome/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../vendors/iconic-fonts/flat-icons/flaticon.css">
    <link rel="stylesheet" href="../vendors/iconic-fonts/cryptocoins/cryptocoins.css">
    <link rel="stylesheet" href="../vendors/iconic-fonts/cryptocoins/cryptocoins-colors.css">
    <!-- Bootstrap core CSS -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery UI -->
    <link href="../assets/css/jquery-ui.min.css" rel="stylesheet">
    <!-- Page Specific CSS (Slick Slider.css) -->
    <link href="../assets/css/slick.css" rel="stylesheet">
    <link href="../assets/css/datatables.min.css" rel="stylesheet">
    <!-- Foodtech styles -->
    <link href="../assets/css/style.css" rel="stylesheet">
    <!-- Homepage styles-->
    <link href="../css/main.css" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="../favicon.ico">
    <!--jQuery Script-->
    <script src="../assets/js/jquery-3.3.1.min.js"></script>
</head>


<body>
    <!-- Overlays -->
    <div class="ms-aside-overlay ms-overlay-left ms-toggler" data-target="#ms-side-nav" data-toggle="slideLeft"></div>
    <!-- Sidebar Navigation Left -->
    <aside id="ms-side-nav" class="side-nav fixed ms-aside-scrollable ms-aside-left">
        <!-- Logo -->
        <div class="logo-sn ms-d-block-lg">
            <a class="pl-0 ml-0 text-center" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" alt="logo">
            </a>
        </div>
        <!-- Navigation -->
        <ul class="accordion ms-main-aside fs-14" id="side-nav-accordion">
            <!-- P3-6 -->
            <li class="menu-item">
                <a href="#" class="has-chevron" data-toggle="collapse" data-target="#dashboard" aria-expanded="false" aria-controls="dashboard">
                    <span><i class="material-icons fs-16">dashboard</i>Restaurants</span>
                </a>
                <ul id="dashboard" class="collapse" aria-labelledby="dashboard" data-parent="#side-nav-accordion">
                    <!-- Continue to add more lines from here -->
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Navigation" asp-action="Index">Navigation</a>
                    </li>
                    <!-- End of adding more lines -->
                </ul>
            </li>
            <!-- /P3-6 -->
            <!-- P3-3 -->
            <li class="menu-item">
                <a href="#" class="has-chevron" data-toggle="collapse" data-target="#tables" aria-expanded="false" aria-controls="tables">
                    <span><i class="material-icons fs-16">tune</i>Itinerary</span>
                </a>
                <ul id="tables" class="collapse" aria-labelledby="tables" data-parent="#side-nav-accordion">
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Itinerary" asp-action="Index">Itinerary</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                    </li>
                </ul>
            </li>
            <!-- /P3-3 -->
            <!-- P3-2 -->
            <li class="menu-item">
                <a href="#" class="has-chevron" data-toggle="collapse" data-target="#maps" aria-expanded="false" aria-controls="maps">
                    <span><i class="material-icons fs-16">map</i>Attractions</span>
                </a>
                <ul id="maps" class="collapse" aria-labelledby="maps" data-parent="#side-nav-accordion">
                    <li>
                        <a href="pages/maps/google-maps.html">Google Maps</a>
                    </li>
                    <li>
                        <a href="pages/maps/vector-maps.html">Vector Maps</a>
                    </li>
                </ul>
            </li>
            <!-- /P3-2 -->
        </ul>
    </aside>

    <div class="container">

        <!-- Navigation Bar -->
        <nav class="navbar ms-navbar">
            <div class="ms-aside-toggler ms-toggler pl-0" data-target="#ms-side-nav" data-toggle="slideLeft">
                <span class="ms-toggler-bar bg-primary"></span>
                <span class="ms-toggler-bar bg-primary"></span>
                <span class="ms-toggler-bar bg-primary"></span>
            </div>
            <ul class="ms-nav-list ms-inline mb-0" id="ms-nav-options">
                <li class="ms-nav-item ms-search-form pb-0 py-0">
                    <form class="ms-form" method="post">
                        <div class="ms-form-group my-0 mb-0 has-icon fs-14">
                            <input type="search" class="ms-form-input" name="search" placeholder="Search here..." value=""> <i class="flaticon-search text-disabled"></i>
                        </div>
                    </form>
                </li>
            </ul>
        </nav>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - personalised_concierge_m1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- SCRIPTS -->
    <!-- Global Required Scripts Start -->
    @*<script src="../assets/js/jquery-3.3.1.min.js"></script>*@
    <script src="../assets/js/popper.min.js"></script>
    
    <script src="../assets/js/bootstrap.min.js"></script>
    <script src="../assets/js/perfect-scrollbar.js">
    </script>
    <script src="../assets/js/jquery-ui.min.js">
    </script>
    <!-- Global Required Scripts End -->
    <!-- Page Specific Scripts Start -->
    <script src="../assets/js/Chart.bundle.min.js">
    </script>
    <script src="../assets/js/widgets.js"></script>
    <script src="../assets/js/clients.js">
    </script>
    <script src="../assets/js/Chart.Financial.js">
    </script>
    <script src="../assets/js/d3.v3.min.js">
    </script>
    <script src="../assets/js/topojson.v1.min.js">
    </script>
    <script src="../assets/js/datatables.min.js"></script>
    <script src="../assets/js/data-tables.js">
    </script>
    <!-- Page Specific Scripts Finish -->
    <!-- Foodtech core JavaScript -->
    <script src="../assets/js/framework.js"></script>
    <!-- Settings -->
    <script src="../assets/js/settings.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>